REmpleados/REmpleados/urls.py
"""
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.Departamentos.urls')),
    re_path('', include('applications.Empleados.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

REmpleados/applications/Departamentos/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'departamentos_app'

urlpatterns = [
    path('list-departamentos/',
    views.DepartamentosListView.as_view(),
    name='listar-departamentos'
),
    path('new-departamento/',
    views.NewDepartamentoForm.as_view(),
    name='nuevo-departamento'
),
]

REmpleados/applications/Empleados/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'empleados_app'

urlpatterns = [
    path('', 
    views.Inicio.as_view(),
    name='inicio'
),
    path('empleados-all/', 
    views.EmpleadosListView.as_view(),
    name='listar_empleados'
),
    path('list-by-area/<shorname>/',
    views.EmpleadosbyDepartamentosListView.as_view(),
    name='listar-por-area'
),
    path('admin-empleados/',
    views.AdminEmpleadosListView.as_view(),
    name='administrar-empleados'
),
    path('update-empleado/<pk>/',
    views.EmpleadosUpdateView.as_view(),
    name='modificar-empleado'
),
    path('delete-empleado/<pk>/',
    views.EmpleadoDeleteView.as_view(),
    name='eliminar-empleado'
),
    path('add-empleado/',
    views.EmpleadoCreateView.as_view(),
    name='nuevo-empleado'
),
    path('detail-empleado/<pk>/',
    views.EmpleadoDetailView.as_view(),
    name='ver-empleado'
),
]

REmpleados/applications/Departamentos/models.py
from django.db import models

# Create your models here.

class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50)
    short_name = models.CharField('Nombre corto', max_length=50)
    anulate = models.BooleanField('Anulado', default = False)

    def __str__(self):
        return self.name + " - " + self.short_name

    class Meta:
        #db_table = ''
        #managed = True
        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'

REmpleados/applications/Empleados/models.py
from django.db import models
from applications.Departamentos.models import Departamento

# Create your models here.
class Habilidades(models.Model):
    habilidades = models.CharField('Habilidades', max_length=50)
    def __str__(self):
        return str(self.id) + " - " + self.habilidades

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades'


class Empleado(models.Model):
    JOB_CHOICES = (
        ('0','Administrador'),
        ('1','Gerente'),
        ('2','Contador'),
        ('3','Docente'),
        ('4','Director'),
        ('5','Almacenero'),
        ('6','Vigilante'),
    )

    first_name = models.CharField('Nombres:', max_length=50)
    last_name = models.CharField('Apellidos:', max_length=50)
    job = models.CharField('Trabajo:', max_length=1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField('Avatar', upload_to='empleados', null=True, blank=True)
    habilidades = models.ManyToManyField(Habilidades)

    def __str__(self):
        return str(self.id) + " - " + self.first_name + " - " + self.last_name

    class Meta:
        #db_table = ''
        #managed = True
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados'

REmpleados/applications/Departamentos/forms.py
from django import forms

class NewDepartamento(forms.Form):
    nombres = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shorname = forms.CharField(max_length=50)

REmpleados/applications/Departamentos/views.py
from django.shortcuts import render
from django.views.generic import (
    ListView,
)
from django.urls import reverse_lazy
from django.views.generic.edit import FormView
from .forms import NewDepartamento
# Create your views here.
from .models import Departamento
from applications.Empleados.models import Empleado

class DepartamentosListView(ListView):
    template_name = "departamentos/list-departamentos.html"
    model = Departamento
    context_object_name = 'ListadoDepartamentos'


class NewDepartamentoForm(FormView):
    template_name = 'departamentos/new-departamento.html'
    form_class = NewDepartamento
    success_url = reverse_lazy('departamentos_app:listar-departamentos')

    def form_valid(self, form):
        depa = Departamento(
            name = form.cleaned_data['departamento'],
            short_name = form.cleaned_data['shorname']
        )
        depa.save()
        newempleado = Empleado(
            first_name = form.cleaned_data['nombres'],
            last_name = form.cleaned_data['apellidos'],
            job = '1',
            departamento = depa
        )
        newempleado.save()
        return super(NewDepartamentoForm, self).form_valid(form)

REmpleados/applications/Empleados/views.py
from django.shortcuts import render
from django.views.generic import (
    TemplateView,
    ListView,
    UpdateView,
    DeleteView,
    CreateView,
    DetailView,
)
# Create your views here.
from django.urls import reverse_lazy

from .models import Empleado


class Inicio(TemplateView):
    template_name = "index.html"


class EmpleadosListView(ListView):
    template_name = "empleados/list-empleados.html"
    #model = Empleado
    paginate_by = 5
    context_object_name = 'ListadoEmpleados'

    def get_queryset(self):
        filtro = self.request.GET.get("nombre",'')
        lista = Empleado.objects.filter(
            first_name__icontains = filtro
        ).order_by('first_name')
        return lista


class EmpleadosbyDepartamentosListView(ListView):
    template_name = "empleados/empleados-by-departamentos.html"
    context_object_name = 'EmpleadosxDepartamento'

    def get_queryset(self):
        filtro = self.kwargs['shorname']
        lista = Empleado.objects.filter(
            departamento__short_name = filtro
        ).order_by('first_name')
        return lista

    def get_context_data(self, **kwargs):
        context = super(EmpleadosbyDepartamentosListView, self).get_context_data(**kwargs)
        context['ndepartamento'] = self.kwargs['shorname']
        return context


class AdminEmpleadosListView(ListView):
    template_name = "empleados/admin_empleados.html"
    model = Empleado
    context_object_name = 'Data'
    ordering = ('first_name')
    paginate_by = 10


class EmpleadosUpdateView(UpdateView):
    template_name = "empleados/update-empleado.html"
    model = Empleado
    fields = ('__all__')
    success_url = reverse_lazy('empleados_app:listar_empleados')


class EmpleadoDeleteView(DeleteView):
    template_name = "empleados/delete-empleado.html"
    model = Empleado
    context_object_name = 'Data'
    success_url = reverse_lazy('empleados_app:listar_empleados')


class EmpleadoCreateView(CreateView):
    template_name = "empleados/add-empleado.html"
    model = Empleado
    fields = ('__all__')
    success_url = reverse_lazy('empleados_app:listar_empleados')


class EmpleadoDetailView(DetailView):
    template_name = "empleados/detail-empleado.html"
    model = Empleado
    context_object_name = 'DatosEmpleado'

REmpleados/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <title>
        {% block titulo %}
          
        {% endblock titulo %}
    </title>
</head>
<body>
    {% block contenido %}
      
    {% endblock contenido %}
    <script src="{% static 'js/app.js' %} "></script>
</body>
</html>

REmpleados/templates/departamentos/list-departamentos.html
{% extends 'base.html' %}

{% block titulo %}
  Listado de Areas
{% endblock titulo %}

{% block contenido %}
  
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h2 class="cell">Listado de Areas de Empresa</h2>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Nombre corto</th>
                        <th>Accion</th>
                    </tr>
                </thead>
                <tbody>
                    {% for elementos in ListadoDepartamentos %}
                    <tr>
                        <td>{{ elementos.id }}</td>
                        <td>{{ elementos.name }}</td>
                        <td>{{ elementos.short_name }}</td>
                        <td>
                            <a href="{% url 'empleados_app:listar-por-area' elementos.short_name %}" class="button warning">Ver Empleados</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock contenido %}

REmpleados/templates/departamentos/new-departamento.html
{% extends "base.html" %}

{% block titutlo %}
  Nuevo Departamento
{% endblock titutlo %}

{% block contenido %}
  
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h2 class="cell">Nuevo Departamento y Empleado</h2>
        <div class="cell callout" style="margin-top: 10;">
            <form method="POST" class="cell grid-x grid-margin-x">{% csrf_token %}
                <h4 class="cell">Datos de Empleado</h4>
                <div class="cell large-6">
                    <label for="">Nombres</label>
                    {{form.nombres}}
                </div>
                <div class="cell large-6">
                    <label for="">Apellidos</label>
                    {{form.apellidos}}
                </div>
                <h4 class="cell">Datos de Departamento</h4>
                <div class="cell large-6">
                    <label for="">Nombre de Departamento</label>
                    {{form.departamento}}
                </div>
                <div class="cell large-6">
                    <label for="">Nombre corto de Departamento</label>
                    {{form.shorname}}
                </div>
                <div class="cell">
                    <button type="submit" class="button success">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock contenido %}

REmpleados/templates/empleados/add-empleado.html
{% extends 'base.html' %}

{% block titulo %}
  Creacion de Nuevo Empleado
{% endblock titulo %}

{% block contenido %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h2 class="cell">Creacion de Nuevo Empleado</h2>
        <form method="POST" class="cell grid-x grid-margin-x" enctype="multipart/form-data">{% csrf_token %}
            <div class="cell large-6">
                <label for="">Nombres
                    {{form.first_name}}
                </label>
            </div>
            <div class="cell large-6">
                <label for="">Apellidos
                    {{form.last_name}}
                </label>
            </div>
            <div class="cell large-6">
                <label for="">Trabajo
                    {{form.job}}
                </label>
            </div>
            <div class="cell large-6">
                <label for="">Departamento
                    {{form.departamento}}
                </label>
            </div>
            <div class="cell large-12">
                <label for="">Habilidades
                    {{form.habilidades}}
                </label>
            </div>
            <div class="cell large-12">
                <label for="">Avatar
                    {{form.avatar}}
                </label>
            </div>
            <div class="cell large-1">
                <button type="submit" class="button success">Guardar</button>
            </div>
            <div class="cell large-1">
                <a href="{% url 'empleados_app:listar_empleados' %}" class="button">Cancelar</a>
            </div>
        </form>
    </div>
</div>

{% endblock contenido %}

REmpleados/templates/empleados/admin_empleados.html
{% extends "base.html" %}

{% load static %}

{% block titulo %} Administracion de Empleados {% endblock titulo %}

{% block contenido %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h2 class="cell">Administración de los Empleados</h2>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th width="100">Foto</th>
                        <th>Nombres</th>
                        <th>Apellidos</th>
                        <th>Trabajo</th>
                        <th>Departamento</th>
                        <th colspan="2">Accion a relizar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for elementos in Data %}
                    <tr>
                        <td>{{ elementos.id }}</td>
                        <td>
                            {% if elementos.avatar %}
                            <img src="{{ elementos.avatar.url }}" alt="">
                            {% else %}
                            <img src="{% static 'img/sin_imagen.jpg' %}" alt="">
                            {% endif %}
                        </td>
                        <td>{{ elementos.first_name }}</td>
                        <td>{{ elementos.last_name }}</td>
                        <td>{{ elementos.get_job_display }}</td>
                        <td>{{ elementos.departamento.short_name }}</td>
                        <td><a class="button success" href="{% url 'empleados_app:modificar-empleado' elementos.id %}">Modificar</a></td>
                        <td><a class="button alert" href="{% url 'empleados_app:eliminar-empleado' elementos.id %}">Eliminar</a></td>
                    </tr> 
                    {% endfor %}
                </tbody>
            </table>
        </div>
        
        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}">Atras</a></li>
                    {% endif %}
                    {% for pagina in paginator.page_range %}
                    
                        {% ifequal pagina page_obj.number %} 
                        <li class="current">{{pagina}}</li>
                        {% else %}
                        <li><a href="?page={{pagina}}">{{ pagina }}</a></li>  
                        {% endifequal %}

                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}">Siguiente</li>
                    {% endif %}                        
                </ul>
            </nav> 
            {% endif %}
        </div>
    </div>
</div>

{% endblock contenido %}

REmpleados/templates/empleados/delete-empleado.html
{% extends 'base.html' %}

{% block titulo %}
 Eliminacion de Empleado
{% endblock titulo %}

{% block contenido %}
  
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h2 class="cell">Eliminacion de Empleado</h2>
        <h4 class="cell">Nombres: {{Data.first_name}}</h4>
        <h4 class="cell">Apellidos: {{Data.last_name}}</h4>
        <div class="cell callout alert" data-closable>
            <h5>¡Esto es importante!</h5>
            <p>But when you're done reading it, click the close button in the corner to dismiss this alert.</p>
            <p>I'm using the default <code>data-closable</code> parameters, and simply fade out.</p>
        </div>
        <form class="cell" method="POST">{% csrf_token %}
            <button type="submit" class="button alert">Eliminar</button>
            <a href="{% url 'empleados_app:administrar-empleados' %}" class="button">Cancelar</a>
        </form>
    </div>
</div>
{% endblock contenido %}

REmpleados/templates/empleados/detail-empleado.html
{% extends "base.html" %}

{% load static %}

{% block titulo %} Detalle de Empleado {% endblock titulo %}

{% block contenido %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell large-4 card" style="width: 300px; margin-top: 10px;">
            <div class="card-divider">
                {{ DatosEmpleado.get_job_display }}
            </div>                
            {% if DatosEmpleado.avatar %}
                <img src="{{ DatosEmpleado.avatar.url}}" alt="">
            {% else %}
                <img src="{% static 'img/sin_imagen.jpg' %}" alt="">
            {% endif %}
                
            <div class="card-section">
                <h4>{{ DatosEmpleado.first_name}} {{ DatosEmpleado.last_name}}</h4>
                <p>{{ DatosEmpleado.first_name }}</p>
                <p>{{ DatosEmpleado.last_name }}</p>
                <p>{{ DatosEmpleado.departamento.short_name}}</p>
                <p><span class="label">Habilidades:</span></p>
                <ul class="vertical menu">
                    {% for h in DatosEmpleado.habilidades.all %}
                    <li>{{h.habilidades}}</li>
                    {% endfor %}  
                </ul>
            </div>
        </div>          
    </div>
</div>

{% endblock contenido %}

REmpleados/templates/empleados/empleados-by-departamentos.html
{% extends 'base.html' %}

{% block titulo %}
  Administracion de Empleados
{% endblock titulo %}

{% block contenido %}
  
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h2 class="cell">Empleados del area de {{ndepartamento}}</h2>
        {% if EmpleadosxDepartamento %}
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombres</th>
                        <th>Apellidos</th>
                        <th>Trabajo</th>
                        <th>Departamento</th>
                        <th>Accion</th>
                    </tr>
                </thead>
                <tbody>
                    {% for elementos in EmpleadosxDepartamento %}
                    <tr>
                        <td>{{elementos.id}}</td>
                        <td>{{elementos.first_name}}</td>
                        <td>{{elementos.last_name}}</td>
                        <td>{{elementos.get_job_display}}</td>
                        <td>{{elementos.departamento.short_name}}</td>
                        <td>
                            <a href="{% url 'empleados_app:ver-empleado' elementos.id %}" class="button warning">Ver</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <div class="cell callout warning" data-closable>
            <h5>No hay ningun Empleado Registrado</h5>
            <p>But when you're done reading it, click the close button in the corner to dismiss this alert.</p>
            <p>I'm using the default <code>data-closable</code> parameters, and simply fade out.</p>
        </div>
            
        {% endif %}
            
    </div>
</div>

{% endblock contenido %}

REmpleados/templates/empleados/list-empleados.html
{% extends "base.html" %}

{% load static %}

{% block titulo %} Listar Empleados {% endblock titulo %}

{% block contenido %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h2 class="cell">Listado de Empleados</h2>
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-5">
                <input type="text" placeholder="Trabajador a buscar" name="nombre">
            </div>
            <div class="cell large-2">
                <button type="submit" class="button success">BUSCAR</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombres</th>
                        <th>Apellidos</th>
                        <th width="120">Foto</th>
                        <th>Trabajo</th>
                        <th>Departamento</th>
                        <th>Accion</th>
                    </tr>
                </thead>
                <tbody>
                    {% for elementos in ListadoEmpleados %}
                    <tr>
                        <td>{{ elementos.id }}</td>
                        <td>{{ elementos.first_name }}</td>
                        <td>{{ elementos.last_name }}</td>
                        <td>                            
                            {% if elementos.avatar %}
                            <img src="{{elementos.avatar.url}}" alt="">
                            {% else %}
                            <img src="{% static 'img/sin_imagen.jpg' %}" alt="">
                            {% endif %}                                
                        </td>
                        <td>{{ elementos.get_job_display }}</td>
                        <td>{{ elementos.departamento.short_name }}</td>
                        <td><a class="button warning" href="{% url 'empleados_app:ver-empleado' elementos.id %}">Ver</a></td>
                    </tr> 
                    {% endfor %}
                </tbody>
            </table>
        </div>
        
        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}">Atras</a></li>
                    {% endif %}
                    {% for pagina in paginator.page_range %}
                    
                        {% ifequal pagina page_obj.number %} 
                        <li class="current">{{pagina}}</li>
                        {% else %}
                        <li><a href="?page={{pagina}}">{{ pagina }}</a></li>  
                        {% endifequal %}

                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}">Siguiente</li>
                    {% endif %}                        
                </ul>
            </nav> 
            {% endif %}
        </div>
    </div>
</div>

{% endblock contenido %}

REmpleados/templates/empleados/update-empleado.html
{% extends 'base.html' %}

{% block titulo %}
  Modificacion de Empleado
{% endblock titulo %}

{% block contenido %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h2 class="cell">Modificacion de Empleado</h2>
        <form method="POST" class="cell grid-x grid-margin-x" enctype="multipart/form-data">{% csrf_token %}
            <div class="cell large-6">
                <label for="">Nombres
                    {{form.first_name}}
                </label>
            </div>
            <div class="cell large-6">
                <label for="">Apellidos
                    {{form.last_name}}
                </label>
            </div>
            <div class="cell large-6">
                <label for="">Trabajo
                    {{form.job}}
                </label>
            </div>
            <div class="cell large-6">
                <label for="">Departamento
                    {{form.departamento}}
                </label>
            </div>
            <div class="cell large-6">
                <label for="">Habilidades
                    {{form.habilidades}}
                </label>
            </div>
            <div class="cell large-6">
                <label for="">Avatar
                    {{form.avatar}}
                </label>
            </div>
            <div class="cell large-1">
                <button type="submit" class="button success">Guardar</button>
            </div>
            <div class="cell large-1">
                <a href="{% url 'empleados_app:administrar-empleados' %}" class="button">Cancelar</a>
            </div>
        </form>
    </div>
</div>

{% endblock contenido %}

REmpleados/templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
            <a class="menu-text" href="/">Empleados</a>
            <li><a href="{% url 'empleados_app:listar_empleados' %}">Listar</a></li>
            <li><a href="{% url 'departamentos_app:listar-departamentos' %}">Departamentos</a></li>
            <li><a href="{% url 'empleados_app:administrar-empleados' %}">Administrar</a></li>
            <li><a href="{% url 'departamentos_app:nuevo-departamento' %}">Nuevo Departamento</a></li>
        </ul>
    </div>
    <div class="top-bar-right">
        <ul class="menu">
            <li><input type="search" placeholder="Buscar Empleado"></li>
            <li><a href="{% url 'empleados_app:nuevo-empleado' %}" class="button">Nuevo Empleado</a></li>
        </ul>
    </div>
</div>  

REmpleados/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %} Inicio de Pagina {% endblock titulo %}

{% block contenido %}

{% include "includes/header.html" %}

<!-- Inicio de Imagen de Portada  -->
<div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
    <div class="orbit-wrapper">
      <div class="orbit-controls">
        <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
        <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
      </div>
      <ul class="orbit-container">
        <li class="is-active orbit-slide">
          <figure class="orbit-figure">
            <img class="orbit-image" src="{% static '/img/5.png' %}" alt="Space">
            <figcaption class="orbit-caption">Glorioso Fornitet.</figcaption>
          </figure>
        </li>
        <li class="orbit-slide">
          <figure class="orbit-figure">
            <img class="orbit-image" src="{% static '/img/6.jpg' %}" alt="Space">
            <figcaption class="orbit-caption">Fondo.</figcaption>
          </figure>
        </li>
      </ul>
    </div>
</div>
<!-- Fin de Imagen de Portada -->

<!-- Bloque de Bienvenida -->
<div class="grid-x align-center">
    <h1 class="cell large-8" style="font-size: 25px; text-align: center;">Bienvenido al Sistema de Registro de Empleados</h1>
    <div class="cell large-7">
        <div class="callout success">
            <h5>Resgistra y controla empleados</h5>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur aspernatur inventore quidem error eius odit sit minus rem amet dolorum nihil perspiciatis dignissimos, quo quae excepturi dolores eligendi cumque impedit.</p>
            <a href="#">Ver empleados</a>
        </div>
    </div>
</div>
<!-- fin de bloque de bienvenida -->

{% endblock contenido %}